apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-nas
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nas-smb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-nas
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nas-smb
