apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Warsaw"
        - name: WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: webui
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads

      - name: firefox
        image: lscr.io/linuxserver/firefox:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Warsaw"
        ports:
        - containerPort: 3000
          name: firefox-http
        - containerPort: 3001
          name: firefox-https
        volumeMounts:
        - name: firefox-config
          mountPath: /config
        - name: downloads
          mountPath: /downloads

      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config-local
      - name: downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads-tank-bulk
      - name: firefox-config
        persistentVolumeClaim:
          claimName: qbittorrent-firefox-config

      nodeSelector:
        kubernetes.io/hostname: g3-worker3
