apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
  - port: 8080
    targetPort: 8080
    name: webui
  type: LoadBalancer
  loadBalancerIP: 192.168.50.54
---
apiVersion: v1
kind: Service
metadata:
  name: firefox
  namespace: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
  - port: 3000
    targetPort: 3000
    name: firefox-http
  - port: 3001
    targetPort: 3001
    name: firefox-https
  type: LoadBalancer
  loadBalancerIP: 192.168.50.55
