apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
        - name: TZ
          value: "Europe/Warsaw"
        - name: WEBPASSWORD
          value: "admin"
        - name: DNSMASQ_LISTENING
          value: "all"
        - name: PIHOLE_DNS_
          value: "8.8.8.8;8.8.4.4"
        - name: DNSMASQ_USER
          value: "root"
        - name: FTLCONF_dns_listeningMode
          value: "ALL"
        ports:
        - containerPort: 80
          name: web
        - containerPort: 443
          name: web-https
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: dnsmasq-data
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: pihole-data
      - name: dnsmasq-data
        persistentVolumeClaim:
          claimName: dnsmasq-data
      nodeSelector:
        kubernetes.io/hostname: pi4-worker2
