apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: market-exporter
  namespace: market
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: market-exporter
  endpoints:
    - port: metrics
      interval: 60s
