apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arr-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/buth11/pi-homelab.git
    targetRevision: main
    path: k8s/arr
  destination:
    server: https://kubernetes.default.svc
    namespace: arr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
