apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      nodeSelector:
        kubernetes.io/hostname: g3-worker3
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:latest
        ports:
        - containerPort: 80
        args:
        - --database=/config/filebrowser.db
        - --root=/srv
        volumeMounts:
        - name: media
          mountPath: /srv
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /srv/Downloads
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: jellyfin-media-v2
      - name: config
        persistentVolumeClaim:
          claimName: filebrowser-config
      - name: downloads
        persistentVolumeClaim:
          claimName: filebrowser-downloads
